<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ScanFlowOcr.Contracts/ScanFlowOcr.Contracts.csproj" />
    <PackageReference Include="BitMiracle.LibTiff.NET" />
    <PackageReference Include="StbImageSharp" />
    <PackageReference Include="StbImageWriteSharp" />
  </ItemGroup>
</Project>
