<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Sdcb.SimdPaddleOCR" Version="1.3.0" />
    <PackageVersion Include="Sdcb.SimdPaddleOCR.ModelProvider" Version="1.0.0" />
    <PackageVersion Include="Sdcb.SimdPaddleOCR.Models.ChineseV6Tiny" Version="1.0.0" />
    <PackageVersion Include="Sdcb.SimdPaddleOCR.Models.ChineseV6Small" Version="1.0.0" />
    <PackageVersion Include="Sdcb.SimdPaddleOCR.Models.TextLineOrientation" Version="1.0.0" />
    <PackageVersion Include="BitMiracle.LibTiff.NET" Version="2.4.649" />
    <PackageVersion Include="StbImageSharp" Version="2.30.15" />
    <PackageVersion Include="StbImageWriteSharp" Version="1.16.7" />
    <PackageVersion Include="Avalonia" Version="11.3.6" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.6" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.6" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.6" />
  </ItemGroup>
</Project>
