<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ScanFlowOcr.Contracts/ScanFlowOcr.Contracts.csproj" />
    <ProjectReference Include="../ScanFlowOcr.Imaging/ScanFlowOcr.Imaging.csproj" />
  </ItemGroup>
</Project>
